### ISSUE TITLE
Stars not showing

### ISSUE THREAD

**Issue by cooletijdgast** [sebsebmc/starlink-coverage#13]
The stars representing that a area has 100% coverage only show when you set the a minimum angle to load the dataset to 25 degrees, when you set that to 35 degrees it doesn't show any stars where it should show them.

De first picture shows the 35 degrees option, and the second picture shows the 25 degrees option
![sternietzien](https://user-images.githubusercontent.com/47114377/90323865-5a6deb00-df67-11ea-8fc2-5eaa6494cab6.PNG)
![sterwelzien](https://user-images.githubusercontent.com/47114377/90323866-5b068180-df67-11ea-8eda-35133435b435.PNG)

Thanks anyway for the awesome website!

**Comment by sebsebmc** [comment]
> when you set that to 35 degrees it doesn't show any stars where it should show them.

Currently there are no cells that have 100% uptime when simulating coverage with a 35 degree minimum user terminal angle, so no stars should show up when selecting 35 degrees.
