### ISSUE TITLE
perigee > 540

### ISSUE THREAD

**Issue by hirokun2016** [sebsebmc/starlink-coverage#17]
Hi,
   Thank you for your this.

    Just wanted to ask, what is the reason why you exclude satellites with perigee less than 540?

Regards,
Bryan

**Comment by sebsebmc** [comment]
If you're referring to https://github.com/sebsebmc/starlink-coverage/blob/5d22365b918a523852a009e72e9fa4d5cb6b465e/main.py#L73 then we're actually only _keeping_ the satellites with a perigee greater than 540km. This lets us only consider the satellites that are near their final positioning and altitude.
