### ISSUE TITLE
Identifying cell IDs within USA

### ISSUE THREAD

**Issue by kgtjan** [sebsebmc/starlink-coverage#28]
Is there is a way for identifying cell IDs that are within US territory?  I am trying to calculate the % coverage for the cells within the US territory.
Do you think the global performance (% coverage) is similar to the performance of the cells in the US territory?

Thanks!!

**Comment by sebsebmc** [comment]
Your best bet for this would be to grab some GeoJSON that maps out the shape of the US. Using H3 you can tesselate that shape and it will spit out cell ids.
